export const NFTs = [
  {
    Id: 1,
    Badge: 'Total Sale: $82,571',
    ImageUrl: '/images/nft/1.jpg',
    Edition: 31,
    Stock: 547,
    Title: 'SKELETON',
    Price: '$56M',
    Avatar: '/images/avatar/angel.jpg',
    Author: 'newk3d',
    Likes: 710,
  },
  {
    Id: 2,
    Badge: 'Total Sale: $82',
    ImageUrl: '/images/nft/2.jpg',
    Edition: 37,
    Stock: 82,
    Title: 'HOUSE',
    Price: '$16M',
    Avatar: '/images/avatar/crypto.jpg',
    Author: 'KING',
    Likes: 224,
  },
  {
    Id: 3,
    Badge: 'Total Sale: $8,571',
    ImageUrl: '/images/nft/3.jpg',
    Edition: 71,
    Stock: 538,
    Title: 'TREE',
    Price: '$13K',
    Avatar: '/images/avatar/lazer.jpg',
    Author: 'FUTURE',
    Likes: 556,
  },
  {
    Id: 4,
    Badge: 'Total Sale: $2,571',
    ImageUrl: '/images/nft/4.jpg',
    Edition: 244,
    Stock: 18,
    Title: 'SMILE',
    Price: '$12M',
    Avatar: '/images/avatar/ugonzo.jpg',
    Author: 'NFTART',
    Likes: 52,
  },
  {
    Id: 5,
    Badge: 'Total Sale: $82,71',
    ImageUrl: '/images/nft/5.jpg',
    Edition: 321,
    Stock: 8,
    Title: 'EYES',
    Price: '$10K',
    Avatar: '/images/avatar/snoop.jpg',
    Author: 'Metaverse',
    Likes: 42,
  },
  {
    Id: 6,
    Badge: 'Total Sale: $571',
    ImageUrl: '/images/nft/bking.png',
    Edition: 51,
    Stock: 128,
    Title: 'BKING',
    Price: '$10M',
    Avatar: '/images/avatar/ugonzo.jpg',
    Author: 'NFTART',
    Likes: 652,
  },
]
